sudo: false
before_install:
- gem update bundler
- bundle --version
language: ruby
cache: bundler
rvm:
- 2.3.4

services:
  - postgresql

before_script:
  - bin/rake db:create
script:
  - bin/rake db:migrate RAILS_ENV=test
  - bin/rake